### ISSUE TITLE
Setup-Problems (Double clicking and stuff)

### ISSUE THREAD

**Issue by Arhu** [Jakllp/MarioKart-1.16plus#3]
Hi, i have tryed to install that plugin for my pappermc server but it doesm't recognize it. plz help me.

**Comment by Jakllp** [comment]
Somehow github didn't show me this issue.
Did it work?

**Comment by Arhu** [comment]
yes it did. I just was dumb and didnt download the jar file i downloaded
the code. Xd.
Thx

Best regards Arhu

to 4. maalisk. 2021 klo 4.03 Jakl (notifications@github.com) kirjoitti:

**Comment by Jakllp** [comment]
Oh I see - Happy racing then!

Sorry again that I didn't answer earlier.

**Comment by Arhu** [comment]
It's ok. But one thing. When i try to mark the finnis/start line it does it
twice so its one block (it double clicks with wand). What do i do?

to 4. maalisk. 2021 klo 20.27 Jakl <notifications@github.com> kirjoitti:

**Comment by Jakllp** [comment]
Ah yes... The good old track setup... I haven't touched that yet but I might improve on it very soon.

So... Everytime it asks you to click WITHOUT the wand you have to take another item (like... a sword) and click on a block.
But when you click something WITH the wand you need to click into the air.
For some reason that I haven't found (yet) it triggers:
- Twice when clicking a block with the wand
- Not at all when clicking the air without a wand
- Twice when clicking a block with an empty hand

**Comment by Arhu** [comment]
Ok, thx mate.

pe 5. maalisk. 2021 klo 3.12 Jakl <notifications@github.com> kirjoitti:

**Comment by Jakllp** [comment]
Improved in newest version - clicking into the air without an item in hand still doesn't work as that is a Bukkit/Minecraft thing

**Comment by Arhu** [comment]
It doesn't work

**Comment by Arhu** [comment]
i have still the problemo

**Comment by Jakllp** [comment]
It's still doing double clicks?

**Comment by Arhu** [comment]
the vehicle spawn work

**Comment by Arhu** [comment]
next the goal

**Comment by Arhu** [comment]
and the check points

**Comment by Arhu** [comment]
IT WORKS

**Comment by Arhu** [comment]
sry i just saw the new version didnt look that up. sry

**Comment by Arhu** [comment]
THX

**Comment by Jakllp** [comment]
No problem ^^

Glad it is working now!

**Comment by Arhu** [comment]
btw do you wanna get mentioned in our school minecraft tournament?

**Comment by Arhu** [comment]
This hole thing is for the tournament

**Comment by Jakllp** [comment]
Ohh interesting! Nice school you've got there - I'm guessing northern europe?
*is now really hoping everything will work the way it's intended to work*

If you want to mention me you can which everyone good luck and a good race from me.
But I'll leave that decision up to you.

**Comment by Jakllp** [comment]
If you need any more help I've actually recently setup an (empty) Discord-Server for Github-Repo-related things:
https://discord.gg/mF7GpK2vJU

If you don't have Discord/don't want it you can just keep messaging me here tho.

**Comment by Arhu** [comment]
We are from Finland. But ok, gonna mention you. Thx
